import type { Metadata } from "next";
import "./globals.css";
import { WalletProviders } from "@/app/components/WalletProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  children,}: Readonly<{  children: React.ReactNode;}>) {
 
  return (
    <html lang="en">
      <body>
       <WalletProviders>
          {children}
        </WalletProviders>
      </body>
    </html >
  );
}
